get-native-asset:
	stellar contract id asset --asset native

XLM_TOKEN := CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC
# VAULT_TOKEN := CBVCWGCLJA2WI3QUNG45XAVS7H6SQZIIHMUNMFGHCMVBM2DW4RONMJ4U
VAULT_TOKEN := CDR74AGHPT3NR4DWGWXLQLDILSMVSFLZGVETNJGZ7YZ3LPYGUYWGC75M
VRF_TOKEN := CDR74AGHPT3NR4DWGWXLQLDILSMVSFLZGVETNJGZ7YZ3LPYGUYWGC75M


deploy:
	stellar contract invoke \
		--id CD37RGHZDIXBWCTKBDCAOBWXFQLKCHS7XUZ6DB3F2PYLDO3VSLCZKRQH \
		--source raffle-deployer \
		--network testnet \
		-- \
		init \
		--admin raffle-deployer \
		--token $(XLM_TOKEN) \
		--vault $(VAULT_TOKEN)

stellar contract invoke \
  --id CCHYE7T3N6OAOOPJ4BOL7ANBBEK7H4FVYTFQXPFMJSH7CG2J6Y6WBOCV \
  --source-account raffle-deployer \
  --network testnet \
  -- \
  init \
  --admin raffle-deployer \
  --token CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC \
  --vault CDR74AGHPT3NR4DWGWXLQLDILSMVSFLZGVETNJGZ7YZ3LPYGUYWGC75M